### ISSUE TITLE
[FE] test: 각 컴포넌트의 Storybook을 작성한다.

### ISSUE THREAD

**Issue by regularPark** [woowacourse-teams/2023-stamp-crush#118]
## 구현 기능

- 컴포넌트별로 작성되지 않은 스토리북을 작성한다. 

<br/>

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by 2yunseong** [comment]
테스트 전략 변경으로 인한 close
