### ISSUE TITLE
[BE] feat: DB 데이터를 drop할 수 없음

### ISSUE THREAD

**Issue by yenawee** [woowacourse-teams/2023-stamp-crush#236]
## 구현 기능

<br/>

- 3차 데모데이 권장 사항
- 기능 구현 완료 후 진행 예정
- 변경이 발생했을 때 데이터를 지워야 한다면, 새로운 table을 만들고 migration하는 것까지가 DB 데이터 drop 관련 내용임!

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [ ] `milestone` 설정

<br/>

**Comment by eunkeeee** [comment]
어떻게 하게 될 지 궁금하네요! ㅎㅎ

**Comment by eunkeeee** [comment]
# 권한 설정을 통해서 drop을 못하도록 강제함
