### ISSUE TITLE
[FE] refactor: 고객 모드의 화면을 PC환경에서도 모바일뷰로 렌더링한다.

### ISSUE THREAD

**Issue by regularPark** [woowacourse-teams/2023-stamp-crush#278]
## 리팩터링 내용

- 고객 모드의 화면을 PC환경에서도 모바일뷰로 렌더링한다.

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by kangyeongmin** [comment]
구현완료이므로 닫겠습니다!
