### ISSUE TITLE
[BE] refactor: Coupon관련 service 계층 테스트 수정

### ISSUE THREAD

**Issue by youngh0** [woowacourse-teams/2023-stamp-crush#336]
## 리팩터링 내용

- 팀 컨벤션에 맞게 테스트를 수정할 계획입니다.
- service계층만 해도 코드 변화가 많을 것 같아 controller, service계층에 대해 각각 이슈를 남겨 수정할 계획입니다.

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by eunkeeee** [comment]
넹! 저도 컨트롤러 서비스 따로 남기겠슴당
