### ISSUE TITLE
[BUG] 쿠폰 상세페이지 엑스박스

### ISSUE THREAD

**Issue by splitCoding** [woowacourse-teams/2023-stamp-crush#353]
## 버그 기능

아래에 있는 ...  을 눌르고 나서 상세페이지에 들어가면 엑스박스가 뜨네요ㅠ

 ## 버그 상황 
<img width="387" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/75476562/8d97509f-f6be-41a3-9f82-a18a2d44a117">

 ## 기대 동작
엑스박스 대신 의도하신 이미지가 로딩되었으면 좋겠어요!

**Comment by ukkodeveloper** [comment]
<img width="493" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/109048739/4955f52d-b239-42a5-a021-a12045ec2d28">
