### ISSUE TITLE
쿠폰 제작 및 변경 페이지 동작 오류

### ISSUE THREAD

**Issue by Creative-Lee** [woowacourse-teams/2023-stamp-crush#359]
## 버그 기능
![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/77152650/7583701b-dc5b-4d08-97d9-e0c033d86dff)

 ## 버그 상황 
쿠폰 제작 및 변경 페이지에서 **쿠폰 앞/뒷면, 스탬프 선택**이 잘 안되는 것 같아요.

 ## 기대 동작
 - 이미지 엑스박스와 선택기능 플로우에 대해 설명이 있었으면 어떻게 사용할지 감이 더 잘올것 같고, 동작했으면 좋겠습니다~

**Comment by kangyeongmin** [comment]
#357 과 동일하므로 닫겠습니다!
