### ISSUE TITLE
카페 설명 수정이 모든 카페에 적용이 됩니다.

### ISSUE THREAD

**Issue by hanueleee** [woowacourse-teams/2023-stamp-crush#361]
## 버그 기능
![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/91522259/1c9b93c4-8fad-4bf7-b0ed-2861215fb95a)
![image](https://github.com/woowacourse-teams/2023-stamp-crush/assets/91522259/f1f22c1c-6b4d-4759-9bba-c7184f28e77d)

 ## 버그 상황 
 - 사장님 버전의 `내 카페 관리`에서 소개글을 수정했더니, 고객 버전의 모든 카페 쿠폰의 소개글이 변경됩니다.

 ## 기대 동작
 - 해당 카페의 소개글만 바뀌어야 할 것 같아요.

**Comment by kangyeongmin** [comment]
#358 과 동일하게 카페 정보 조회 api 에 잘못된 index가 들어가서 생기는 문제이므로 닫겠습니다.
