### ISSUE TITLE
고객 스탬프 적립 시 새로고침 해야 반영이 됩니다

### ISSUE THREAD

**Issue by xodms0309** [woowacourse-teams/2023-stamp-crush#362]
## 버그 기능
 - 고객 스탬프 적립

 ## 버그 상황 
 - 주신 번호로 적립을 했을 때 고객 페이지로 이동하고 새로고침을 해야 반영이 됩니다!

 ## 기대 동작
 - 새로고침을 안해도 반영되어야 할 것 같습니다.

**Comment by 2yunseong** [comment]
고객목록
