### ISSUE TITLE
고객의 리워드 수가 맞지 않는 것 같습니다

### ISSUE THREAD

**Issue by xodms0309** [woowacourse-teams/2023-stamp-crush#364]
## 버그 기능
 - 고객의 리워드 수가 안 맞는 거같아요
<img width="927" alt="스크린샷 2023-08-07 오후 2 39 57" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/55427367/7124de7a-c683-4dd2-9e4a-5ea543993b29">
<img width="812" alt="스크린샷 2023-08-07 오후 2 40 07" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/55427367/e934d692-9ec7-410f-8eca-6fea6ca35614">

 ## 버그 상황 
 - 고객의 리워드가 메인 페이지에서는 11개고 사용을 하러 들어가면 없다고 뜹니다! 그리고 사용 테스트도 해봤는데 차감이 안되는 것 같습니다.

 ## 기대 동작
 - 리워드 수가 일치하고 차감이 되어야 할 것 같습니다.

**Comment by kangyeongmin** [comment]
감사합니다.
백엔드에서 관련한 버그 수정 이슈를 팠기 때문에 닫겠습니다.
