### ISSUE TITLE
기능 건의) 고객 모드 메인 페이지 카페 목록 빠르게 확인하기 

### ISSUE THREAD

**Issue by 70825** [woowacourse-teams/2023-stamp-crush#365]
버그는 아닌데 기능 추가하면 좋을 것 같아서 여기에 올릴게요!

## 기능 건의 사항
 - 현재 고객 모드 메인 페이지에서 다음 카페로 이동하려면 클릭을 한 번씩 해야합니다. 하지만 사용자가 수많은 카페 도장을 가지고 있으면 너무 불편할 것 같아요. 그래서 휠로 빠르게 원하는 카페를 빠르게 찾을 수 있으면 좋을 것 같습니다. 사실 지금 카페 3개인데도 레고 카페로 이동하는데 2초 정도 걸려서 조금 불편하긴해요

**Comment by kangyeongmin** [comment]
일단 사용자가 수많은 카페도장을 가지고 있을 확률이 매우 희박합니다.
다른 모드를 개발하기에는 현재 기능 구현 우선순위에서 밀리므로, 그때 대응하기로 내부 결론이 나서 닫겠습니다!
