### ISSUE TITLE
[FE] feat: 각 페이지의 로딩/에러 상태를 대응한다.

### ISSUE THREAD

**Issue by 2yunseong** [woowacourse-teams/2023-stamp-crush#394]
## 구현 기능

<br/>

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

## 주의사항
- 그렇게 급한 이슈는 아님
- 고객모드 우선 적용

**Comment by kangyeongmin** [comment]
레고가 완료했으므로 닫겠습니다~
