### ISSUE TITLE
[FE] refactor: api 메소드에 하드코딩된 Header Authorization을 제거한다.

### ISSUE THREAD

**Issue by kangyeongmin** [woowacourse-teams/2023-stamp-crush#403]
## 리팩터링 내용

<br/>

## 체크리스트

- [] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by 2yunseong** [comment]
OAuth 전까지는 안해도 될 것 같습니다 @regularPark

**Comment by kangyeongmin** [comment]
레벨4로 이동하겠습니다
