### ISSUE TITLE
[BE] refactor: 테스트 코드 패키지 manager, visitor 구조로 변경

### ISSUE THREAD

**Issue by eunkeeee** [woowacourse-teams/2023-stamp-crush#407]
## 리팩터링 내용

<br/>

## 체크리스트

- [ ] `assignee` 설정 (선택)
- [ ] `labels` 설정
- [ ] `milestone` 설정

<br/>

**Comment by yenawee** [comment]
https://github.com/woowacourse-teams/2023-stamp-crush/pull/430

완료
