### ISSUE TITLE
[BE] feat: 프로필 별 log설정을 분리한다

### ISSUE THREAD

**Issue by youngh0** [woowacourse-teams/2023-stamp-crush#538]
## 구현 기능

- dev, prod별로 로그 레벨 분리할 예정입니다.

<br/>

## 작업 내용

- logback-spring.xml 파일을 수정해서 prod는 INFO레벨,dev는 DEBUG레벨까지 출력하도록 수정할 예정입니다.
<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x]  `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by eunkeeee** [comment]
## 적용 잘 되는지 확인해주세요

@youngh0
