### ISSUE TITLE
[BE] bug: 사장의 고객 목록 조회 시 방문이력이 없는 경우 예외 대신 빈 리스트를 반환하도록 해야한다.

### ISSUE THREAD

**Issue by youngh0** [woowacourse-teams/2023-stamp-crush#541]
## 버그설명

- `/api/admin/cafes/{cafeId}/customers` API에서 조회할 고객이 없어도 빈 리스트를 반환해야 한다.
  - 그러나, 방문한 고객에 대한 쿠폰만 만들고 스탬프 적립을 안한 경우 방문 이력이 안생기고 VisitHistories를 만드는 과정에서 예외를 발생시킨다. 첫 방문 일자를 구해야하는데 VisitHistory 데이터가 없으면 첫 방문 일자를 구할 수 없어서 예외를 던지는 상황

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by yenawee** [comment]
https://github.com/woowacourse-teams/2023-stamp-crush/pull/550

임시방편으로 해결

근데 수정해야 함 (첫 방문일 현재 날짜로 반환, 방문횟수 0번으로 계산됨)

**Comment by yenawee** [comment]
방문이력 없으면 고객 목록 조회 응답에 포함 안되게끔
분기문 추가

```
if (visitHistories.getVisitCount() == 0) {
            continue ;
}
```
