### ISSUE TITLE
[FE] bug: 카페 background 이미지를 등록했음에도 랜덤으로 변하는 문제 

### ISSUE THREAD

**Issue by eunkeeee** [woowacourse-teams/2023-stamp-crush#562]
## 버그 기능
 - 페이지 캡쳐나, 기능을 적어주세요.

<img width="1582" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/5c7554cc-7d4f-42b8-bad4-e739a48ea5a8">

위와 같이 직접 카페 백그라운드 사진을 등록함.

이후에 고객모드에서 1트에는 그대로 잘 나옴

<img width="1582" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/ba44b33c-ef58-4a4a-9544-9ab51cc22829">

잠시 후, 글 내용을 수정했더니 갑자기 배경만 랜덤으로 변해버림 ㅠㅠ

<img width="1582" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/af23944e-ca6e-40f5-870f-47b6e8bc103c">

 ## 버그 상황 
 - 버그 상황에 대해서 간단히 설명해 주세요.

 ## 기대 동작
 - 기대했던 동작에 대해서 설명해 주세요.

**Comment by regularPark** [comment]
해결하였으므로 close합니다!
