### ISSUE TITLE
[FE] bug: 리워드 사용 진입 시 임시회원일 경우를 방어하지 않음

### ISSUE THREAD

**Issue by 2yunseong** [woowacourse-teams/2023-stamp-crush#568]
## 버그설명

<br/>

## 체크리스트

- [ ] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by yenawee** [comment]
임시 회원도 리워드 사용 가능해야 해서 할필요 없어짐
