### ISSUE TITLE
[FE] feat: 사장모드에서 존재하지 않는 전화번호 입력 시 자동으로 임시회원을 생성하지 말고, 한 번 수동 절차로 alert 를 띄워준다

### ISSUE THREAD

**Issue by eunkeeee** [woowacourse-teams/2023-stamp-crush#603]
## 구현 기능

현재 로직: 사장모드에서 스탬프 적립에서 전화번호를 입력했을 때, 존재하지 않는 전화번호이면 곧바로 임시 회원을 생성해 버린다.    
하지만, 실제 상황에서는 잘못해서 입력할 수도 있기 때문에 임시로 회원가입을 할 지에 대해서 한 번 물어보는 절차가 필요할 것 같음. 

## 작업 내용

스탬프 적립 화면에서 전화번호를 눌렀을때 customers 빈배열이 온다면 alert 를 띄워줍시다

ex. 010-1234-5678 로 임시 가입하시겠습니까 ?

## 체크리스트

- [ ] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by yenawee** [comment]
카페 등록 페이지에서 인증하기 빼버리고 사업자 등록번호 정보 받아두기만 하기로 결정

- 9/5 회의록 참고!

**Comment by yenawee** [comment]
#622  와 동일한 이슈이므로 클로즈
