### ISSUE TITLE
[ALL] feat: 사업자 등록번호 입력만 받고, 카페 생성은 당장 안해줌. 그 사이에 우리가 수동으로 검토 

### ISSUE THREAD

**Issue by eunkeeee** [woowacourse-teams/2023-stamp-crush#608]
## 구현 기능

- 과외 앱에서 선생님의 학교 인증을 할 때나, B2B 서비스에서는 인증할 수 있는 서류를 등록하면 24시간 이내에 승인하는 방식처럼 처리하는 경우가 많다. 
- 우리도, 사업자 등록번호 입력 받자마자 카페 생성하는 것이 아니라, 좀 기다리라는 페이지 (진행상황 보여주면 베스트) 보여주고, 수동으로 승인해주는 것이 좋을 것 같음.
- 근데 사장님 admin이 아니라 진짜 개발자 어드민을 만들어야 함. (대충이라도)

<br/>

## 작업 내용

<br/>

## 체크리스트

- [ ] `assignee` 설정 (선택)
- [ ] `labels` 설정
- [ ] `milestone` 설정

<br/>

**Comment by yenawee** [comment]
카페 등록 페이지에서 인증하기 빼버리고 사업자 등록번호 정보 받아두기만 하기로 결정

9/5 회의록 참고!
