### ISSUE TITLE
[FE] bug: 쿠폰 제작 및 변경에서 템플릿/커스텀 버튼이 눌리지 않는 오류

### ISSUE THREAD

**Issue by 2yunseong** [woowacourse-teams/2023-stamp-crush#647]
## 버그 기능
쿠폰 제작 및 변경 템플릿/커스텀 버튼이 눌리지 않는 오류가 있습니다.
 ## 버그 상황 
쿠폰 제작 및 변경 => 커스텀 선택 -> 다음 -> 이전 -> 템플릿 누르면 템플릿이 눌러지지 않음

 ## 기대 동작
페이지 이동과 상관없이 잘 눌려야 될 것 같습니다.

**Comment by regularPark** [comment]
제 새끼 제가 책임지겠습니다😭

**Comment by 2yunseong** [comment]
현재 제가 처리중입니다!
