### ISSUE TITLE
[BE] feat: 전화번호로 유저 프로필 조회 및 리워드 조회 E2E 테스트 작성

### ISSUE THREAD

**Issue by jundonghyuk** [woowacourse-teams/2023-stamp-crush#718]
## 구현 기능
1. 전화번호로 유저 프로필 조회 테스트 작성
2. 리워드 조회 테스트 작성
<br/>

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by yenawee** [comment]
https://github.com/woowacourse-teams/2023-stamp-crush/pull/719
