### ISSUE TITLE
[FE/BE] feat: 스탬프 적립 0개를 막는다

### ISSUE THREAD

**Issue by yenawee** [woowacourse-teams/2023-stamp-crush#825]
## 구현 기능

<br/>

- 스탬프 적립 0개를 막습니다
- max 적립 개수 전에 정한대로 10개로 합니다 (프론트는 되어있음 백에서도 막기!)

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by eunkeeee** [comment]
이거 내가 일단 빨리 만들어서 올려볼게
