### ISSUE TITLE
[BE] hotfix: 스탬프 적립 시 카페 슬랙 메시지에 카페 이름을 추가한다.

### ISSUE THREAD

**Issue by youngh0** [woowacourse-teams/2023-stamp-crush#828]
## 구현 기능

스탬프 적립 슬랙 메시지에 스탬프 발급 카페 이름 추가

<br/>

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by eunkeeee** [comment]
young ho good luck to you

**Comment by yenawee** [comment]
완료
