### ISSUE TITLE
[FE] feat: 프로젝트 소개 페이지를 구현한다. 

### ISSUE THREAD

**Issue by kangyeongmin** [woowacourse-teams/2023-stamp-crush#864]
## 구현 기능

<br/>

## 작업 내용

<br/>

## 체크리스트

- [x] `assignee` 설정 (선택)
- [x] `labels` 설정
- [x] `milestone` 설정

<br/>

**Comment by 2yunseong** [comment]
제공받은 Google Sites 를 이용해 구현 완료
