### ISSUE TITLE
[FE] feat: 카페 소개 페이지에서 description 표시 (스크롤바 등장 ㅠㅠ)

### ISSUE THREAD

**Issue by eunkeeee** [woowacourse-teams/2023-stamp-crush#865]
## 구현 기능

글이 길어지면 스크롤바가 등장해서 글이 안보이고, 내리는 것도 못생겨보여서
스크롤바를 없애거나 차라리 글이 많아지면 제한하는 방식이 나을 것 같습니당! 

<img width="378" alt="image" src="https://github.com/woowacourse-teams/2023-stamp-crush/assets/107979804/c482cf59-81af-4418-86b2-ae92d5507978">

<br/>

## 작업 내용

<br/>

## 체크리스트

- [ ] `assignee` 설정 (선택)
- [ ] `labels` 설정
- [ ] `milestone` 설정

<br/>

**Comment by eunkeeee** [comment]
@kangyeongmin @2yunseong @regularPark 
이문제 최종데모 전에 해결 가능할까요..?!!?!

**Comment by kangyeongmin** [comment]
해결완료 이슈이므로 닫겠습니다~
